version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Cleanup front-end container
      - aws s3 rm s3://cfmt-frontend --recursive
      - echo Cleanup successful
      - echo Upload front-end
      - aws s3 cp ./build s3://cfmt-frontend --recursive --acl public-read
      - echo Frontend uploaded successfully
      - echo Invalidate cloudfront distribution
      - aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id E1APOTSYKRJKB --paths /*
      - echo Invalidation successfully requested
artifacts:
  files:
    - build/**/*
  discard-paths: yes