version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
    post_build:
  commands:
      - echo Cleanup front-end container
      - aws s3 rm s3://cfmt-frontend --recursive
artifacts:
  files:
    - build/**/*
  discard-paths: yes