export const ACTIVACTION_CODES = {
  USERNAME: 'USERNAME',
  LDAPUSERNAME: 'LDAPUSERNAME',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PWD: 'PWD',
  LDAPPWD: 'LDAPPWD'
}

export const ALLOWED_RESULTS = {
  REQUIRED: 'REQUIRED',
  NEXT_STEP: 'NEXT_STEP',
  WRONG_VALUE: 'WRONG_VALUE',
  ROBOT_SMELL: 'ROBOT_SMELL'
}
