export const AS_INIT = 'AS_INIT'
export const AS_MODULE_LOADED = 'AS_MODULE_LOADED'
export const AS_MODULE_UNLOAD = 'AS_MODULE_UNLOAD'

export const AS_SET_AUTH_DEVICE_ID = 'AS_SET_AUTH_DEVICE_ID'

export const AS_SHARED_SET = 'AS_SHARED_SET'
export const AS_SHARED_RESET = 'AS_SHARED_RESET'

export const AS_AGENDA_SET_KEY = 'AS_AGENDA_SET_KEY'
export const AS_AGENDA_SET = 'AS_AGENDA_SET'

export const AS_GET_CODELIST_REQUEST = 'AS_GET_CODELIST_REQUEST'
export const AS_GET_CODELIST_SUCCESS = 'AS_GET_CODELIST_SUCCESS'

export const AS_LOCALISATION_FETCHED = 'AS_LOCALISATION_FETCHED'
export const AS_LOCALISATION_LANGUAGE = 'AS_LOCALISATION_LANGUAGE'
export const AS_LOCALISATION_RELOADED = 'AS_LOCALISATION_RELOADED'

export const AS_REGISTER_ENDPOINTS = 'AS_REGISTER_ENDPOINTS'
