export const AS_AUTH_TOKEN_KEY = 'AS_AUTH_TOKEN'
export const AS_AUTH_TOKEN_EXPIRATION = 'AS_AUTH_TOKEN_EXPIRATION'
export const AS_AUTH_SESSION = 'AS_AUTH_SESSION'
export const AS_AUTH_DEVICE_ID = 'deviceId'
