export const AS_AUTH_JWT  = 'apollo_jwt'

export const AS_API_CALL_DEFAULT_PROXY = '/'

export const AS_API_LOGGED_OFF_NOTIFICATION_ID = 'AS_LOGGED_OFF_FOR_SECURITY_REASON'

export const AS_API_CALL = '@@api/CALL'
export const AS_API_MODULE_CALL = '@@api/MODULE_CALL'
export const AS_API_UNKNOWN_METHOD = '@@api/UNKNOWN_METHOD'
export const AS_API_INVALID_ACTION = '@@api/INVALID_ACTION'
export const AS_API_FORBIDDEN = '@@api/FORBIDDEN'

export const AS_API_OK_STATUS = 200
export const AS_API_ERROR_STATUS_BAD_REQUEST = 400
export const AS_API_ERROR_STATUS_UNAUTHORIZED = 401
export const AS_API_ERROR_STATUS_FORBIDDEN = 403
export const AS_API_ERROR_STATUS_NOT_FOUND = 404
export const AS_API_ERROR_STATUS_TOO_LARGE = 413
export const AS_API_ERROR_STATUS_ADDITIONAL_AUTHORIZATION_REQUIRED = 418
export const AS_API_ERROR_STATUS_SERVER_ERROR = 500
